/-
Copyright (c) 2026 Michal Wallace. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michal Wallace
-/

import RationalTangles.IntegerTangle
import RationalTangles.Flip

/-!
# Flypes and diagram isotopy

A flype is an isotopy of a 2-tangle applied on a 2-subtangle of the form
`[±1] + t` or `[±1] * t` (Kauffman–Lambropoulou Definition 2, Figure 5).
It fixes the endpoints of the subtangle. Combinatorially the replacement is

```
[±1] + t  ↦  t^{hflip} + [±1]
[±1] * t  ↦  t^{vflip} * [±1]
```

After the flipping lemma, a *rational* flype is the commutation
`[±1] + t ∼ t + [±1]` (and likewise for `*`).

Diagram isotopy is the equivalence generated by Reidemeister moves in the
interior of the disc (including planar isotopy), flypes, congruence of
addition and multiplication, and conjugation by flips. The last two families
are the standard fact that an isotopy of a subtangle (or of a spatially
rotated copy) is an isotopy of the whole diagram.
-/

namespace RationalTangles

/-- One flype of a 2-tangle, in the direction that moves the `[±1]` twist
    from the left (resp. top) to the right (resp. bottom), flipping the
    subtangle `t` as in Figure 5. -/
inductive Flype : TangleDiagram → TangleDiagram → Prop where
  | add_pos (t : TangleDiagram) :
      Flype (one.add t) (t.hflip.add one)
  | add_neg (t : TangleDiagram) :
      Flype (negOne.add t) (t.hflip.add negOne)
  | mul_pos (t : TangleDiagram) :
      Flype (one.mul t) (t.vflip.mul one)
  | mul_neg (t : TangleDiagram) :
      Flype (negOne.mul t) (t.vflip.mul negOne)

/-- A flype in either direction. -/
def IsFlype (D E : TangleDiagram) : Prop :=
  Flype D E ∨ Flype E D

/-- Diagram isotopy of 2-tangles. -/
inductive Isotopic : TangleDiagram → TangleDiagram → Prop where
  | refl (D : TangleDiagram) : Isotopic D D
  | step {D E : TangleDiagram} : ReidemeisterMove D E → Isotopic D E
  | trans {D E F : TangleDiagram} : Isotopic D E → Isotopic E F → Isotopic D F
  | symm {D E : TangleDiagram} : Isotopic D E → Isotopic E D
  | flype {D E : TangleDiagram} : IsFlype D E → Isotopic D E
  | add_left {T T' S : TangleDiagram} :
      Isotopic T T' → Isotopic (T.add S) (T'.add S)
  | add_right {T S S' : TangleDiagram} :
      Isotopic S S' → Isotopic (T.add S) (T.add S')
  | mul_left {T T' S : TangleDiagram} :
      Isotopic T T' → Isotopic (T.mul S) (T'.mul S)
  | mul_right {T S S' : TangleDiagram} :
      Isotopic S S' → Isotopic (T.mul S) (T.mul S')
  | hflip_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.hflip T'.hflip
  | vflip_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.vflip T'.vflip
  | hflip_add (T S : TangleDiagram) :
      Isotopic (T.add S).hflip (T.hflip.add S.hflip)
  | hflip_mul (T S : TangleDiagram) :
      Isotopic (T.mul S).hflip (S.hflip.mul T.hflip)
  | vflip_add (T S : TangleDiagram) :
      Isotopic (T.add S).vflip (S.vflip.add T.vflip)
  | vflip_mul (T S : TangleDiagram) :
      Isotopic (T.mul S).vflip (T.vflip.mul S.vflip)
  | invert_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.invert T'.invert
  | invert_add (T S : TangleDiagram) :
      Isotopic (T.add S).invert (S.invert.mul T.invert)
  | invert_mul (T S : TangleDiagram) :
      Isotopic (T.mul S).invert (T.invert.add S.invert)
  | add_assoc (T S R : TangleDiagram) :
      Isotopic ((T.add S).add R) (T.add (S.add R))
  | mul_assoc (T S R : TangleDiagram) :
      Isotopic ((T.mul S).mul R) (T.mul (S.mul R))
  | zero_add (T : TangleDiagram) :
      Isotopic (TangleDiagram.zero.add T) T
  | add_zero (T : TangleDiagram) :
      Isotopic (T.add TangleDiagram.zero) T
  | invert_unit (s : CrossingSign) :
      Isotopic (crossingTangle s) (crossingTangle s).invert
  | mirror_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.mirror T'.mirror
  /-- Transfer move (Figure 14, mixed pair of signs, i odd):
      `(T + [-1]) * [+1] ∼ [+1] + (-T)⁻¹`. -/
  | transfer_odd (T : TangleDiagram) :
      Isotopic ((T.add negOne).mul one) (one.add T.mirror.invert)
  /-- Transfer move with signs switched. -/
  | transfer_odd_neg (T : TangleDiagram) :
      Isotopic ((T.add one).mul negOne) (negOne.add T.mirror.invert)

theorem isotopic_planar {D E : TangleDiagram} (h : PlanarIsotopy D E) :
    Isotopic D E :=
  .step (.isotopy h)

/-! ## Local flype on PD-code (Figure 5)

A distinguished crossing slides to the opposite side of a neighboring
2-subtangle `t`. The box `t` is turned 180° (each crossing `rotate180`,
signs preserved, matching Figure 5). The rest of the diagram is identified
by an injective arc map `f`. The four tangle endpoints stay fixed up to `f`.

This is the local replacement used for coloring transport. It is not the
algebraic `Flype` constructor (`t.hflip` / `t.vflip` switches every crossing
of `t`); reusing `col` after that switch fails `ColoringRule`.
-/

/-- The flype crossing before/after, with matching sign and a distinguished
    over-leg `u` and under-leg `w`. External legs are matched by `f`. -/
structure IsFlypeCrossingSlide (f : Nat → Nat) (FD FE : Crossing)
    (uD wD uE wE : Nat) : Prop where
  adjD : FD.adjacentDistinct
  adjE : FE.adjacentDistinct
  portsD : FD.portsDistinct
  portsE : FE.portsDistinct
  sign : FD.sign = FE.sign
  huwD : uD ≠ wD
  huwE : uE ≠ wE
  overD : FD.isOverArc uD
  underD : FD.isUnderArc wD
  overE : FE.isOverArc uE
  underE : FE.isUnderArc wE
  u_map : uE = f uD
  w_map : wE = f wD
  ext_match : FE.extOverArc uE = f (FD.extOverArc uD)
  und_match : FE.otherUnderArc wE = f (FD.otherUnderArc wD)

/-- Local flype: one crossing slides over a neighboring subtangle whose
    crossings are turned 180°, remainder identified by `f`. -/
def IsLocalFlype (D E : TangleDiagram) : Prop :=
  ∃ (f : Nat → Nat) (FD FE : Crossing) (tD tE restD restE : List Crossing)
      (uD wD uE wE : Nat),
    Function.Injective f ∧
      IsFlypeCrossingSlide f FD FE uD wD uE wE ∧
      E.NW = f D.NW ∧ E.NE = f D.NE ∧ E.SE = f D.SE ∧ E.SW = f D.SW ∧
      D.crossings.Perm (FD :: tD ++ restD) ∧
      E.crossings.Perm (FE :: tE ++ restE) ∧
      pairRel Crossing.sameUpToRotation (restD.map (Crossing.rename f)) restE ∧
      pairRel (fun C Y => (C.rotate180.rename f).sameUpToRotation Y) tD tE ∧
      (∀ C ∈ restE, ¬ C.memArc uE ∧ ¬ C.memArc wE) ∧
      (∀ C ∈ tE, ¬ C.memArc uE ∧ ¬ C.memArc wE)

/-! ## Coloring isotopy

The equivalence generated by the diagram moves that already have coloring
transport: Reidemeister I–II (on well-formed diagrams), local R3 over-slide,
local flype, planar isotopy, and add/mul congruence.

This is *not* `Isotopic`: it omits indexed `IsReidemeisterIII`, algebraic
`Flype` (`hflip`/`vflip`+switch), and the algebraic identities (associativity,
transfer, flip laws). Those generators do not currently carry coloring, so
invariance of `f` is stated for `ColoringIsotopy` rather than for `Isotopic`.
-/

/-- Directed coloring-ready isotopy of 2-tangle diagrams. -/
inductive ColoringIsotopy : TangleDiagram → TangleDiagram → Prop where
  | refl (D : TangleDiagram) : ColoringIsotopy D D
  | trans {D E F : TangleDiagram} :
      ColoringIsotopy D E → ColoringIsotopy E F → ColoringIsotopy D F
  | r1 {D E : TangleDiagram} :
      IsReidemeisterI D E → D.WellFormed → E.WellFormed → ColoringIsotopy D E
  | r2 {D E : TangleDiagram} :
      IsReidemeisterII D E → D.WellFormed → E.WellFormed → ColoringIsotopy D E
  | r3Local {D E : TangleDiagram} :
      IsReidemeisterIIILocal D E → ColoringIsotopy D E
  | localFlype {D E : TangleDiagram} :
      IsLocalFlype D E → ColoringIsotopy D E
  | isotopy {D E : TangleDiagram} :
      PlanarIsotopy D E → ColoringIsotopy D E
  | add_left {T T' S : TangleDiagram} :
      ColoringIsotopy T T' → ColoringIsotopy (T.add S) (T'.add S)
  | add_right {T S S' : TangleDiagram} :
      ColoringIsotopy S S' →
      (S.NW = S.SW → S'.NW = S'.SW) →
      ColoringIsotopy (T.add S) (T.add S')
  | mul_left {T T' S : TangleDiagram} :
      ColoringIsotopy T T' → ColoringIsotopy (T.mul S) (T'.mul S)
  | mul_right {T S S' : TangleDiagram} :
      ColoringIsotopy S S' →
      (S.NW = S.NE → S'.NW = S'.NE) →
      ColoringIsotopy (T.mul S) (T.mul S')

theorem IsReidemeisterI.symm {D E : TangleDiagram} (h : IsReidemeisterI D E) :
    IsReidemeisterI E D := by
  rcases h with h | h
  · exact Or.inr h
  · exact Or.inl h

theorem IsReidemeisterII.symm {D E : TangleDiagram} (h : IsReidemeisterII D E) :
    IsReidemeisterII E D := by
  rcases h with h | h
  · exact Or.inr h
  · exact Or.inl h


end RationalTangles
