/-
Copyright (c) 2026 Michal Wallace. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michal Wallace
-/

import RationalTangles.IntegerTangle
import RationalTangles.Flip

/-!
# Flypes and diagram isotopy

A flype is an isotopy of a 2-tangle applied on a 2-subtangle of the form
`[±1] + t` or `[±1] * t` (Kauffman–Lambropoulou Definition 2, Figure 5).
It fixes the endpoints of the subtangle. Combinatorially the replacement is

```
[±1] + t  ↦  t^{hflip} + [±1]
[±1] * t  ↦  t^{vflip} * [±1]
```

After the flipping lemma, a *rational* flype is the commutation
`[±1] + t ∼ t + [±1]` (and likewise for `*`).

Diagram isotopy is the equivalence generated by Reidemeister moves in the
interior of the disc (including planar isotopy), flypes, congruence of
addition and multiplication, and conjugation by flips. The last two families
are the standard fact that an isotopy of a subtangle (or of a spatially
rotated copy) is an isotopy of the whole diagram.
-/

namespace RationalTangles

/-- One flype of a 2-tangle, in the direction that moves the `[±1]` twist
    from the left (resp. top) to the right (resp. bottom), flipping the
    subtangle `t` as in Figure 5. -/
inductive Flype : TangleDiagram → TangleDiagram → Prop where
  | add_pos (t : TangleDiagram) :
      Flype (one.add t) (t.hflip.add one)
  | add_neg (t : TangleDiagram) :
      Flype (negOne.add t) (t.hflip.add negOne)
  | mul_pos (t : TangleDiagram) :
      Flype (one.mul t) (t.vflip.mul one)
  | mul_neg (t : TangleDiagram) :
      Flype (negOne.mul t) (t.vflip.mul negOne)

/-- A flype in either direction. -/
def IsFlype (D E : TangleDiagram) : Prop :=
  Flype D E ∨ Flype E D

/-- Diagram isotopy of 2-tangles. -/
inductive Isotopic : TangleDiagram → TangleDiagram → Prop where
  | refl (D : TangleDiagram) : Isotopic D D
  | step {D E : TangleDiagram} : ReidemeisterMove D E → Isotopic D E
  | trans {D E F : TangleDiagram} : Isotopic D E → Isotopic E F → Isotopic D F
  | symm {D E : TangleDiagram} : Isotopic D E → Isotopic E D
  | flype {D E : TangleDiagram} : IsFlype D E → Isotopic D E
  | add_left {T T' S : TangleDiagram} :
      Isotopic T T' → Isotopic (T.add S) (T'.add S)
  | add_right {T S S' : TangleDiagram} :
      Isotopic S S' → Isotopic (T.add S) (T.add S')
  | mul_left {T T' S : TangleDiagram} :
      Isotopic T T' → Isotopic (T.mul S) (T'.mul S)
  | mul_right {T S S' : TangleDiagram} :
      Isotopic S S' → Isotopic (T.mul S) (T.mul S')
  | hflip_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.hflip T'.hflip
  | vflip_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.vflip T'.vflip
  | hflip_add (T S : TangleDiagram) :
      Isotopic (T.add S).hflip (T.hflip.add S.hflip)
  | hflip_mul (T S : TangleDiagram) :
      Isotopic (T.mul S).hflip (S.hflip.mul T.hflip)
  | vflip_add (T S : TangleDiagram) :
      Isotopic (T.add S).vflip (S.vflip.add T.vflip)
  | vflip_mul (T S : TangleDiagram) :
      Isotopic (T.mul S).vflip (T.vflip.mul S.vflip)
  | invert_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.invert T'.invert
  | invert_add (T S : TangleDiagram) :
      Isotopic (T.add S).invert (S.invert.mul T.invert)
  | invert_mul (T S : TangleDiagram) :
      Isotopic (T.mul S).invert (T.invert.add S.invert)
  | add_assoc (T S R : TangleDiagram) :
      Isotopic ((T.add S).add R) (T.add (S.add R))
  | mul_assoc (T S R : TangleDiagram) :
      Isotopic ((T.mul S).mul R) (T.mul (S.mul R))
  | zero_add (T : TangleDiagram) :
      Isotopic (TangleDiagram.zero.add T) T
  | add_zero (T : TangleDiagram) :
      Isotopic (T.add TangleDiagram.zero) T
  | invert_unit (s : CrossingSign) :
      Isotopic (crossingTangle s) (crossingTangle s).invert
  | mirror_cong {T T' : TangleDiagram} :
      Isotopic T T' → Isotopic T.mirror T'.mirror
  /-- Transfer move (Figure 14, mixed pair of signs, i odd):
      `(T + [-1]) * [+1] ∼ [+1] + (-T)⁻¹`. -/
  | transfer_odd (T : TangleDiagram) :
      Isotopic ((T.add negOne).mul one) (one.add T.mirror.invert)
  /-- Transfer move with signs switched. -/
  | transfer_odd_neg (T : TangleDiagram) :
      Isotopic ((T.add one).mul negOne) (negOne.add T.mirror.invert)

theorem isotopic_planar {D E : TangleDiagram} (h : PlanarIsotopy D E) :
    Isotopic D E :=
  .step (.isotopy h)

end RationalTangles
