/-
Copyright (c) 2026 Michal Wallace. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michal Wallace
-/

import RationalTangles.Reidemeister

/-!
# 2-tangles and isotopy

A 2-tangle is a combinatorial diagram in the disc: the PD-code type
`TangleDiagram` of two arcs (and finitely many circles) with four fixed
endpoints NW, NE, SE, SW. Throughout, “tangle” means a tangle diagram, as in
Kauffman–Lambropoulou.

Two diagrams are isotopic when they differ by a finite sequence of
Reidemeister moves in the interior of the disc (including planar isotopy),
with the four endpoints held fixed.

The class of 2-tangles is closed under addition `T + S` (place `S` to the
right of `T`, joining NE–NW and SE–SW), multiplication `T * S` (place `S`
below `T`, joining SW–NW and SE–NE), mirror image `-T` (switch every
crossing), rotation `T.rotate` (counterclockwise by 90°), and inversion
`T.invert` (the paper's `Tⁱ := -Tʳ`: mirror of the counterclockwise 90°
rotation).
-/

namespace RationalTangles

/-- A 2-tangle diagram in the disc, with four endpoints in the standard
    NW/NE/SE/SW positions. This is the PD-code type `TangleDiagram`. -/
abbrev TwoTangle := TangleDiagram

/-- Diagram isotopy of 2-tangles: the equivalence generated by Reidemeister
    moves in the interior of the projection disc, endpoints fixed. -/
inductive Isotopic : TangleDiagram → TangleDiagram → Prop where
  | refl (D : TangleDiagram) : Isotopic D D
  | step {D E : TangleDiagram} : ReidemeisterMove D E → Isotopic D E
  | trans {D E F : TangleDiagram} : Isotopic D E → Isotopic E F → Isotopic D F
  | symm {D E : TangleDiagram} : Isotopic D E → Isotopic E D

namespace CrossingSign

/-- Reverse a crossing type: positive ↔ negative. -/
def flip : CrossingSign → CrossingSign
  | .pos => .neg
  | .neg => .pos

@[simp] theorem flip_flip (s : CrossingSign) : s.flip.flip = s := by
  cases s <;> rfl

end CrossingSign

namespace Crossing

/-- The largest arc identifier incident to `C`. -/
def maxArc (C : Crossing) : Nat :=
  max C.a0 (max C.a1 (max C.a2 C.a3))

/-- Switch over and under at a crossing (90° port rotation so that ports
    `0` and `2` remain the overstrand) and reverse the crossing type.
    This is the local picture of taking the mirror image. -/
def switch (C : Crossing) : Crossing :=
  { a0 := C.a1, a1 := C.a2, a2 := C.a3, a3 := C.a0, sign := C.sign.flip }

@[simp] theorem switch_switch (C : Crossing) : C.switch.switch = C.rotate180 := by
  rcases C with ⟨a0, a1, a2, a3, s⟩
  cases s <;> rfl

end Crossing

namespace TangleDiagram

/-- The largest arc identifier appearing in the diagram (crossings or
    boundary). Used to shift a second diagram off the first's names. -/
def maxArc (D : TangleDiagram) : Nat :=
  let b := max D.NW (max D.NE (max D.SE D.SW))
  D.crossings.foldl (fun m C => max m C.maxArc) b

/-- Mirror image `-T`: switch over and under at every crossing. Endpoints
    stay put. In particular `-[n] = [-n]`. -/
def mirror (T : TangleDiagram) : TangleDiagram :=
  { T with crossings := T.crossings.map Crossing.switch }

/-- Counterclockwise rotation of `T` by 90°. Crossing PD-data is local
    (ports are relative to the overstrand), so only the four endpoints
    cycle: NW ← NE ← SE ← SW ← NW. -/
def rotate (T : TangleDiagram) : TangleDiagram :=
  { T with NW := T.NE, NE := T.SE, SE := T.SW, SW := T.NW }

/-- Inversion `Tⁱ := -Tʳ`: rotate counterclockwise by 90°, then mirror.
    For integer tangles this produces the corresponding vertical tangle. -/
def invert (T : TangleDiagram) : TangleDiagram :=
  T.rotate.mirror

/-- Place `S` to the right of `T`, joining `T.NE` to `S.NW` and `T.SE` to
    `S.SW`. The sum of two 2-tangles is a 2-tangle; it is rational iff at
    least one summand is an integer tangle. -/
def add (T S : TangleDiagram) : TangleDiagram :=
  let S' := S.rename (· + (T.maxArc + 1))
  let f (a : Nat) : Nat :=
    if a = S'.NW then T.NE
    else if a = S'.SW then T.SE
    else a
  let S'' := S'.rename f
  { crossings := T.crossings ++ S''.crossings
    NW := T.NW
    NE := S''.NE
    SE := S''.SE
    SW := T.SW }

/-- Place `S` below `T`, joining `T.SW` to `S.NW` and `T.SE` to `S.NE`. -/
def mul (T S : TangleDiagram) : TangleDiagram :=
  let S' := S.rename (· + (T.maxArc + 1))
  let f (a : Nat) : Nat :=
    if a = S'.NW then T.SW
    else if a = S'.NE then T.SE
    else a
  let S'' := S'.rename f
  { crossings := T.crossings ++ S''.crossings
    NW := T.NW
    NE := T.NE
    SE := S''.SE
    SW := S''.SW }

end TangleDiagram

instance : Add TangleDiagram := ⟨TangleDiagram.add⟩
instance : Mul TangleDiagram := ⟨TangleDiagram.mul⟩
instance : Neg TangleDiagram := ⟨TangleDiagram.mirror⟩

/-- `[0]ʳ = [∞]`. -/
theorem rotate_zero :
    TangleDiagram.zero.rotate = TangleDiagram.infinity :=
  rfl

/-- `[0]ⁱ = [∞]`. -/
theorem invert_zero :
    TangleDiagram.zero.invert = TangleDiagram.infinity :=
  rfl

end RationalTangles
