/* Generated by autoform render. Edits are overwritten. */
(function () {
  var CLASSDEFS = {
  "light": [
    "classDef mathlib fill:#1C5C33,stroke:#134426,color:#FFFFFF,stroke-width:2px",
    "classDef fully_proved fill:#31A24C,stroke:#22773A,color:#FFFFFF,stroke-width:2px",
    "classDef proved fill:#8ED4A2,stroke:#22773A,color:#0B2415,stroke-width:2px",
    "classDef defined fill:#C3E9CE,stroke:#22773A,color:#0B2415,stroke-width:2px",
    "classDef can_prove fill:#FFFFFF,stroke:#0064E0,color:#0064E0,stroke-width:2px",
    "classDef stated fill:#FFFFFF,stroke:#31A24C,color:#22773A,stroke-width:2px",
    "classDef can_state fill:#FFFFFF,stroke:#0082FB,color:#0B4EA2,stroke-width:2px",
    "classDef not_ready fill:#FFF3D6,stroke:#B77900,color:#5C3D00,stroke-width:2px",
    "classDef planned fill:#FFFFFF,stroke:#CED0D4,color:#65676B,stroke-width:2px",
    "classDef scope fill:#EBF2FE,stroke:#0064E0,color:#050505,stroke-width:2px",
    "classDef boundary fill:#FFFFFF,stroke:#8A8D91,color:#65676B,stroke-width:2px,stroke-dasharray:5 3",
    "classDef focus stroke:#F7B928,stroke-width:4px"
  ],
  "dark": [
    "classDef mathlib fill:#10281A,stroke:#42B72A,color:#8BE78B,stroke-width:2px",
    "classDef fully_proved fill:#13301E,stroke:#42B72A,color:#8BE78B,stroke-width:2px",
    "classDef proved fill:#122A1B,stroke:#31A24C,color:#6BD97F,stroke-width:2px",
    "classDef defined fill:#122A1B,stroke:#2B8F44,color:#6BD97F,stroke-width:2px",
    "classDef can_prove fill:#101F33,stroke:#2D88FF,color:#7FB8FF,stroke-width:2px",
    "classDef stated fill:#18191A,stroke:#31A24C,color:#E4E6EB,stroke-width:2px",
    "classDef can_state fill:#18191A,stroke:#2D88FF,color:#E4E6EB,stroke-width:2px",
    "classDef not_ready fill:#2E2205,stroke:#F7B928,color:#FFD772,stroke-width:2px",
    "classDef planned fill:#18191A,stroke:#4E4F50,color:#B0B3B8,stroke-width:2px",
    "classDef scope fill:#1C1D1F,stroke:#2D88FF,color:#E4E6EB,stroke-width:2px",
    "classDef boundary fill:#18191A,stroke:#8A8D91,color:#B0B3B8,stroke-width:2px,stroke-dasharray:5 3",
    "classDef focus stroke:#F7B928,stroke-width:4px"
  ]
};
  if (typeof mermaid === "undefined") return;
  // The map sits in a panel of the page's own colour, so the diagram supplies
  // no background of its own and borrows the site's type and rules.
  var FONT = '"Plus Jakarta Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif';
  function variables(mode) {
    return mode === "dark"
      ? { background: "transparent", lineColor: "#8A8D91", primaryTextColor: "#E4E6EB",
           mainBkg: "#242526", clusterBkg: "transparent", edgeLabelBackground: "#242526" }
      : { background: "transparent", lineColor: "#8A8D91", primaryTextColor: "#050505",
           mainBkg: "#FFFFFF", clusterBkg: "transparent", edgeLabelBackground: "#FFFFFF" };
  }
  mermaid.initialize({
    startOnLoad: false, securityLevel: "loose", theme: "neutral",
    fontFamily: FONT, themeVariables: variables("light")
  });

  var counter = 0;
  var blocks = Array.prototype.map.call(
    document.querySelectorAll(".mermaid"),
    function (element) { return { element: element, source: element.textContent }; }
  );

  function scheme() {
    return document.body.getAttribute("data-md-color-scheme") === "slate" ? "dark" : "light";
  }

  function draw() {
    var mode = scheme();
    mermaid.initialize({
      startOnLoad: false,
      securityLevel: "loose",
      theme: mode === "dark" ? "dark" : "neutral",
      fontFamily: FONT,
      themeVariables: variables(mode)
    });
    blocks.forEach(function (block) {
      var source = block.source + "\n" + CLASSDEFS[mode].join("\n");
      mermaid.render("bp-graph-" + counter++, source).then(function (result) {
        block.element.innerHTML = result.svg;
        if (result.bindFunctions) result.bindFunctions(block.element);
      });
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", draw);
  } else {
    draw();
  }

  new MutationObserver(function (mutations) {
    mutations.forEach(function (mutation) {
      if (mutation.attributeName === "data-md-color-scheme") draw();
    });
  }).observe(document.body, { attributes: true });
})();
